services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - server-custom
    ports:
      - "80:80"
    depends_on:
      - node_app

  node_app:
    build:
      context: ./node
    container_name: node_app
    networks:
      - server-custom
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db

  mysql-db:
    container_name: mysql-db
    image: "mysql:5.7"
    environment:
      - MYSQL_MASTER_HOST=mysql-db
      - MYSQL_DATABASE=nodedb
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - datamysql:/data/mysql
    networks:
      - server-custom

networks:
  server-custom:
    driver: bridge

volumes:
  datamysql:
    driver: local
